//
//  HarnessFlowModel.swift
//  AppAttestTestApp
//
//  Drives AppAttestKit's real AttestationCoordinator against real
//  DCAppAttestService calls, under the development App Attest environment
//  (AppAttestTestApp.entitlements).
//
//  Calls ONLY the module's production API — restore(), ensureAttested(),
//  sign(), acknowledgeKeyInvalidation() — the same four calls the real app
//  will make. There is no harness-only entry point into the flow: testing a
//  DEBUG-only "attest but don't register" path would be testing code that
//  never ships. Step-by-step control comes from the transport instead (see
//  ControllableTransport.swift), which is app-owned by design.
//
//  Which server (if any) it talks to is a debug setting (TransportBackend).
//
//  Reads NOTHING from AppAttestKit except its public surface — never
//  LiveKeyStore/AttestationKeyStore directly.
//

import Foundation
import CryptoKit
import AppAttestKit

@Observable @MainActor
final class HarnessFlowModel {
    enum ActiveStep { case none, identity, register, sign }

    private(set) var identityGenerated = false
    /// The coordinator's own state, mirrored — updated live from the observer
    /// while a flow runs (so a paused flow shows where it actually is) and
    /// re-read from the coordinator after every call.
    private(set) var moduleState: AttestationState = .none
    private(set) var activeStep: ActiveStep = .none
    private(set) var identityPublicKeyPrefix: String?

    /// Step control: per-endpoint pause / failure injection. See
    /// ControllableTransport.swift.
    let gate = TransportGate()

    var attested: Bool { moduleState.isAttested }

    /// The environment Apple's OWN response reported for the attestation the
    /// current state rests on — `nil` when there is no attestation yet, or
    /// none this install has seen. Drives the banner badge, so the badge is
    /// evidence rather than a label: it cannot say "development" unless an
    /// attestation object actually carried the development aaguid.
    ///
    /// Remembered in UserDefaults because the attestation object itself is
    /// deleted once the server confirms it — without this, a relaunch into
    /// `.attested` would have nothing left to read the answer from.
    /// UserDefaults (not Keychain) so a reinstall forgets it.
    var attestationEnvironment: AttestationEnvironment? {
        switch moduleState {
        case .attestationPending, .attested:
            return lastSeenEnvironment
        case .none, .keyGenerated, .unsupported:
            return nil
        }
    }
    private static let lastSeenEnvironmentKey = "harness.lastAttestationEnvironment"
    private var lastSeenEnvironment: AttestationEnvironment? =
        UserDefaults.standard.string(forKey: lastSeenEnvironmentKey).flatMap(AttestationEnvironment.init(rawValue:)) {
        didSet { UserDefaults.standard.set(lastSeenEnvironment?.rawValue, forKey: Self.lastSeenEnvironmentKey) }
    }

    /// Local heuristic only — Apple exposes no remaining-budget API
    /// (confirmed against current docs this session). Counts real
    /// generateKey() calls via the .keyGenerated transition — but only
    /// while a register() call is actually in flight (see recordTransition);
    /// a bare restore() can ALSO transition into .keyGenerated by reading an
    /// existing keyId off disk, with no real generateKey() call involved.
    /// Keychain-backed, not UserDefaults, so it survives reinstall — the
    /// real budget it's tracking does too.
    var realAttemptCount: Int {
        RealAttemptCounter.keysGenerated.load()
    }

    /// Successful `attestKey()` calls — the only registration step that
    /// reaches Apple's servers. Counted the same way: only while a
    /// register() call is in flight, so restoring a cached attestation on
    /// launch is not mistaken for a new one.
    var appleAttestationCount: Int {
        RealAttemptCounter.appleAttestations.load()
    }

    /// One entry per attempt. "Reset module state" and "Delete identity key"
    /// close out the current session and open a fresh one.
    var sessions: [HarnessSession] = [HarnessSession()]

    var stateLabel: String {
        switch moduleState {
        case .none:
            return identityGenerated ? "none (identity ready)" : "none"
        case .attestationPending:
            return "attestationPending (awaiting /register)"
        default:
            return moduleState.label
        }
    }

    /// Changing this doesn't touch identity/attestation state — those
    /// reflect the DEVICE's own Keychain-persisted state, independent of
    /// which server it's pointed at. Switching backends mid-session and then
    /// tapping Sign against a server that's never seen this device's keyId
    /// is expected to fail server-side — that's correct, not a harness bug.
    var transportBackend: TransportBackend {
        get { TransportBackend.current }
        set {
            guard newValue != TransportBackend.current else { return }
            guard activeStep == .none else {
                // The running flow holds the OLD transport; swapping under it
                // would leave two coordinators writing the same Keychain state.
                log(.backendSwitched, summary: "ignored — finish or reset the running step first", isError: true)
                return
            }
            TransportBackend.current = newValue
            // Cached coordinator holds the OLD transport — drop it so the
            // next resolveCoordinator() rebuilds (and restores) against the
            // new backend.
            coordinator = nil
            log(.backendSwitched, summary: "switched to \(newValue.displayName)")
        }
    }

    private var coordinator: AttestationCoordinator?
    private static let hasLaunchedBeforeKey = "harness.hasLaunchedBefore"
    private let firstLaunchGate = FirstLaunchPurgeGate.standard(key: hasLaunchedBeforeKey)
    private var firstLaunchTask: Task<Void, Never>?

    /// Call once when the view appears.
    ///
    /// First checks whether this is the first launch after an install OR a
    /// reinstall (the `UserDefaults` flag is absent either way — wiped along
    /// with the rest of the sandbox container on delete, unlike Keychain).
    /// If so, purges any stale Keychain leftovers from a PREVIOUS install
    /// before showing any state — this is the proactive half of the v1
    /// policy (appattestkit-module-design.md §8): the UI should never show a
    /// misleadingly "attested" status after a reinstall, even briefly.
    /// `sign()`'s own `acknowledgeKeyInvalidation()` call remains as a
    /// reactive safety net for invalidation that happens WITHOUT a reinstall
    /// (e.g. a device restore) — this gate does not replace it.
    ///
    /// Otherwise (normal, non-first launch), just reflects whatever's
    /// already persisted — critical for the kill-and-relaunch smoke test
    /// (appattest-smoke-checklist.md item 4): without this, the UI would
    /// always show "not started" even after a real prior attestation.
    func restoreOnAppear() async {
        let coordinator = await resolveCoordinator()
        await runFirstLaunchGateOnce(coordinator: coordinator)

        identityGenerated = IdentityKeyStore.exists()
        if let key = (try? IdentityKeyStore.loadExisting()) ?? nil {
            identityPublicKeyPrefix = key.publicKey.rawRepresentation.prefix(4)
                .map { String(format: "%02x", $0) }.joined()
        }
        await coordinator.restore()
        let state = await coordinator.currentState
        moduleState = state
        guard identityGenerated || state != .none else { return }
        // Structured, not just embedded in the summary text — HarnessSession
        // needs to reliably tell "restored into an already-attested state"
        // apart from "restored into something else," and matching against
        // free text would be fragile.
        log(.restored, summary: "found existing state on launch: \(state.label)",
            detail: [DetailField(label: "Restored as attested", value: state.isAttested ? "yes" : "no")])
    }

    /// Deduplicates concurrent calls the same way
    /// `AttestationCoordinator.ensureAttested()` does (an in-flight `Task`)
    /// — `restoreOnAppear()` being invoked more than once concurrently
    /// (today there's one call site, but this is exactly the multi-trigger
    /// shape — launch, foreground, connectivity change — the module's own
    /// docs anticipate for `ensureAttested()`) must not let the purge run
    /// twice.
    ///
    /// Deliberately does NOT reset `firstLaunchTask` to `nil` after
    /// completion the way the coordinator resets `inFlight` — the
    /// coordinator needs to support meaningful NEW runs later (state can
    /// change between calls), but this gate is a true "at most once per
    /// launch" check: once it's resolved, every later call in this same
    /// process should just re-await the same finished `Task` for free,
    /// rather than re-doing even the cheap `UserDefaults` read.
    private func runFirstLaunchGateOnce(coordinator: AttestationCoordinator) async {
        if let firstLaunchTask {
            await firstLaunchTask.value
            return
        }
        let task = Task {
            await self.firstLaunchGate.runIfNeeded {
                // Conditional on purge is required, not optional: a genuine
                // first-ever install ALSO has this flag absent, with nothing
                // in Keychain to purge. Calling acknowledgeKeyInvalidation()
                // unconditionally here would spend a real generateKey() call
                // on a brand-new user's first launch for nothing.
                let hadIdentity = IdentityKeyStore.exists()
                if hadIdentity {
                    IdentityKeyStore.delete()
                }
                await coordinator.restore()
                let hadModuleState = await coordinator.currentState != .none
                if hadModuleState {
                    // Always succeeds now — no regeneration cap to exhaust.
                    // (Earlier revisions could fail here and needed a
                    // harness-only debug-reset fallback; removed along with
                    // the cap itself, see account-keys-reference.md.)
                    await coordinator.acknowledgeKeyInvalidation()
                }
                if hadIdentity || hadModuleState {
                    // Stale from whatever registration this Keychain state
                    // belonged to — a reinstall guarantees the NEXT
                    // registration (if any) will mint a different
                    // account_uuid (v1: no re-attestation), so keeping the
                    // old one around would let sign() try to open a session
                    // for an account this device can no longer prove it owns.
                    RegisteredAccountStore.current = nil
                    self.log(.identityKeyDeleted,
                             summary: "first launch after install/reinstall — purged stale Keychain state from a previous install")
                    self.startNewSession()
                } else {
                    self.log(.restored, summary: "first launch — Keychain already clean, nothing to purge")
                }
            }
        }
        firstLaunchTask = task
        await task.value
    }

    func generateIdentity() async {
        guard activeStep == .none else { return }
        activeStep = .identity
        defer { activeStep = .none }
        do {
            let key = try IdentityKeyStore.loadOrCreate()
            let prefix = key.publicKey.rawRepresentation.prefix(4)
                .map { String(format: "%02x", $0) }.joined()
            identityGenerated = true
            identityPublicKeyPrefix = prefix
            log(.identityKeyGenerated, summary: "identity key ready (\(prefix)…)",
                detail: [DetailField(label: "Public key prefix", value: prefix)])
        } catch {
            log(.identityKeyGenerationFailed, summary: "\(error)", isError: true)
        }
    }

    /// THE production flow, unmodified: one `ensureAttested()` call, which
    /// resumes from whatever state is persisted and runs to `.attested` or
    /// to an error. To stop it part-way, set a pause or a failure in Step
    /// control BEFORE tapping — then tap again to watch it resume, exactly as
    /// a relaunch or a foreground trigger would in the real app.
    func register() async {
        guard activeStep == .none else { return }
        guard identityGenerated, IdentityKeyStore.exists() else {
            log(.attestationFailed, summary: "no identity key — generate one first", isError: true)
            return
        }
        activeStep = .register
        defer { activeStep = .none }

        let coordinator = await resolveCoordinator()
        log(.attestationStarted, summary: "ensureAttested() called — starting from \(await coordinator.currentState.label)")
        do {
            // clientDataHash = SHA256(challenge) alone, NOT SHA256(challenge +
            // identityPublicKey): the server's verification library fixes
            // this formula, so the identity binding lives server-side (the
            // challenge is issued bound to an identityPublicKey and checked
            // back at /register — see RealAttestationTransport.swift).
            let result = try await coordinator.ensureAttested { challenge in
                Data(SHA256.hash(data: challenge))
            }
            if !result.isAttested {
                log(.attestationFailed, summary: "ended in state: \(result.label)", isError: true)
            }
        } catch let error as AttestationError {
            log(.attestationFailed, summary: "ensureAttested() threw \(error.diagnosticName)", isError: true)
        } catch is CancellationError {
            log(.attestationFailed, summary: "ensureAttested() cancelled by a reset", isError: true)
        } catch {
            log(.attestationFailed, summary: "\(error)", isError: true)
        }
        // Whatever happened, show where the module ACTUALLY ended up — this
        // is the thing each test case is checking.
        moduleState = await coordinator.currentState
        log(.restored, summary: "state after ensureAttested(): \(moduleState.label)")
    }

    /// The Secure Enclave signing itself is cheap, repeatable, purely local,
    /// no network at all (confirmed via web search this session). Whether
    /// this ALSO opens a real session against the Auth Server depends on the
    /// backend — .mock never did and still doesn't (nothing to submit to);
    /// .localDocker/.custom now actually call /session/nonce + /session,
    /// which they did NOT do before this was found and fixed: this used to
    /// fabricate a nonce locally and sign it with no server involved at all,
    /// under ANY backend — "Assertion Signed" could appear in History with
    /// no /session request ever reaching the server. See SessionClient.swift.
    func sign() async {
        guard activeStep == .none else { return }
        activeStep = .sign
        defer { activeStep = .none }
        let coordinator = await resolveCoordinator()
        do {
            switch transportBackend {
            case .mock:
                let nonce = Data((0..<32).map { _ in UInt8.random(in: 0...255) })
                let signature = try await coordinator.sign(Data(SHA256.hash(data: nonce)))
                log(.assertionSigned, summary: "assertion signed, mock only — no server involved (\(signature.count) bytes)",
                    detail: [DetailField(label: "Signature size", value: "\(signature.count) bytes")])
            case .localDocker, .custom:
                guard let accountUuid = RegisteredAccountStore.current else {
                    log(.signFailed, summary: "no stored account UUID — Attest must complete successfully first", isError: true)
                    return
                }
                let client = SessionClient(
                    baseURL: currentBaseURL(),
                    signer: coordinator,
                    onEvent: { [weak self] event in
                        Task { @MainActor in self?.handleTransportEvent(event) }
                    })
                // No explicit success log here, deliberately — matching how
                // register() doesn't log the transport-level success either: the real
                // events (.challengeFetched, .sessionOpened, ...) come
                // through onEvent as they actually happen, so logging again
                // here would duplicate the one that matters.
                _ = try await client.openSession(accountUuid: accountUuid)
            }
        } catch let error as AttestationError {
            log(.signFailed, summary: error.diagnosticName, isError: true)
            // Confirmed on real hardware (a delete+reinstall's orphaned keyId):
            // Apple's generateAssertion() surfaces this as DCError.invalidInput
            // → .serverRejected("invalidInput"), NOT .keyInvalid as originally
            // assumed — see the warning in AttestationError.swift this proved
            // right. Safe to treat as equivalent to .keyInvalid specifically
            // HERE: this call's clientDataHash is always a freshly-computed
            // SHA256 digest, never app-malformed, so an "invalidInput" rejection
            // at THIS call site can only mean the keyId itself is dead.
            if error == .keyInvalid || error == .serverRejected("invalidInput") {
                // v1 policy (appattestkit-module-design.md §8, revised): wipe
                // the identity key TOGETHER with module state, always — never
                // one without the other. The earlier version of this handler
                // only called acknowledgeKeyInvalidation(), which is exactly
                // the gap that method closes, but preserving identity here
                // would reintroduce the two-path complexity that decision
                // deliberately traded away for a faster v1 ship.
                IdentityKeyStore.delete()
                RegisteredAccountStore.current = nil
                identityPublicKeyPrefix = nil
                await coordinator.acknowledgeKeyInvalidation()
                identityGenerated = false
                moduleState = await coordinator.currentState
                log(.identityKeyDeleted,
                    summary: "key invalidation acknowledged — identity and module state both cleared (v1 policy), next Generate/Attest starts fully fresh")
                startNewSession()
            }
        } catch {
            log(.signFailed, summary: "\(error)", isError: true)
        }
    }

    /// Clears App Attest state only, via the module's PRODUCTION reset
    /// (`acknowledgeKeyInvalidation()`) — the identity key is kept. Not a
    /// real v1 recovery path by itself (v1 always wipes both together); a
    /// diagnostic for exercising the module from `.none` in isolation.
    ///
    /// Deliberately NOT gated on `activeStep`: this is how a paused or
    /// endlessly-retrying flow gets aborted. The coordinator cancels that
    /// flow and waits for it before clearing anything.
    func resetModuleState() async {
        let coordinator = await resolveCoordinator()
        await coordinator.acknowledgeKeyInvalidation()
        RegisteredAccountStore.current = nil
        lastSeenEnvironment = nil
        moduleState = await coordinator.currentState
        log(.moduleReset, summary: "module state cleared — identity key kept. Next Register spends a real key generation.")
        startNewSession()
    }

    /// The v1 policy in one button: identity key and module state go together.
    func deleteIdentityKey() async {
        // Module first: an in-flight flow must be stopped BEFORE the identity
        // key disappears from under its transport.
        let coordinator = await resolveCoordinator()
        await coordinator.acknowledgeKeyInvalidation()
        IdentityKeyStore.delete()
        RegisteredAccountStore.current = nil
        identityGenerated = false
        identityPublicKeyPrefix = nil
        lastSeenEnvironment = nil
        moduleState = await coordinator.currentState
        log(.identityKeyDeleted, summary: "identity key and module state cleared — next Register starts fully fresh")
        startNewSession()
    }

    // MARK: - Wiring

    /// A freshly built coordinator is restored before anyone uses it: its
    /// in-memory state starts at `.none`, and `sign()` reads only that.
    /// (`ensureAttested()` would rebuild from disk by itself; `sign()`, the
    /// thin hot path, deliberately does not.)
    private func resolveCoordinator() async -> AttestationCoordinator {
        if let coordinator { return coordinator }
        let transport = makeTransport()
        let observer = HarnessObserver(
            onTransition: { [weak self] state in
                Task { @MainActor in self?.recordTransition(state) }
            },
            onFailure: { [weak self] error, attempt in
                Task { @MainActor in
                    // The detail carries the error's associated text (Apple's
                    // DCError code name, or the endpoint + HTTP status) — never a
                    // keyId. Without it every Apple failure reads just "retryable".
                    self?.log(.attestationFailed, summary: "\(error.diagnosticName) (attempt \(attempt))",
                              detail: [DetailField(label: "Error", value: String(describing: error))],
                              isError: true)
                }
            })
        let coordinator = AttestationCoordinator(transport: transport, observer: observer)
        self.coordinator = coordinator
        await coordinator.restore()
        return coordinator
    }

    private func makeTransport() -> AttestationTransport {
        // Never creates: a key that vanished mid-flow must surface as a
        // server-side rejection, not be silently replaced by a new identity.
        let identityPublicKeyBase64: @Sendable () -> String = {
            guard let key = (try? IdentityKeyStore.loadExisting()) ?? nil else { return "" }
            return key.publicKey.rawRepresentation.base64EncodedString()
        }
        let onEvent: @Sendable (TransportEvent) -> Void = { [weak self] event in
            Task { @MainActor in self?.handleTransportEvent(event) }
        }
        let base: AttestationTransport
        switch transportBackend {
        case .mock:
            base = LocalFakeTransport(onEvent: onEvent)
        case .localDocker, .custom:
            base = RealAttestationTransport(
                baseURL: currentBaseURL(),
                identityPublicKeyBase64: identityPublicKeyBase64,
                onEvent: onEvent)
        }
        // Every backend goes through Step control — with both endpoints on
        // "Pass through" it is a plain pass-through.
        return ControllableTransport(base: base, gate: gate, onEvent: onEvent)
    }

    /// Shared by makeTransport() and sign()'s real-backend branch — both
    /// need to agree on which server they're pointed at.
    private func currentBaseURL() -> URL {
        switch transportBackend {
        case .mock, .localDocker: return AuthServerConfig.baseURL
        case .custom(let url): return url
        }
    }

    /// `.label` (used for the summary line and `stateLabel`) is deliberately
    /// keyId-omitting. The ONE deliberate exception is the `.keyGenerated`
    /// case below, which puts the real keyId in a structured DetailField —
    /// needed to visually confirm the SAME key survives a retry loop
    /// (confirmed necessary on a real device: B3's cellular-only run showed
    /// 5 "key generated" log lines for one real generateKey() call, and
    /// proving they shared a keyId was the only way to confirm it). Safe
    /// specifically because this history is in-memory only, same as the raw
    /// CBOR hex below (which embeds the device's real App Attest public
    /// key) — never persisted, synced, or sent to a crash reporter. Do not
    /// extend this exception to anything that outlives this in-memory list.
    private func recordTransition(_ newState: AttestationState) {
        moduleState = newState
        switch newState {
        case .none:
            break
        case .keyGenerated(let keyId):
            // The coordinator reports each state once (no repeat per retry),
            // so inside a running Register this transition means one real
            // generateKey() call. Outside one it is restore() reading an
            // existing keyId back off disk — no Secure Enclave work at all,
            // and must not be logged or counted as a generation. Nothing is
            // logged for it here: on an ordinary launch restoreOnAppear()
            // already reports "found existing state on launch", and on the
            // first launch after a reinstall the key is about to be purged,
            // so announcing it would only be noise.
            guard activeStep == .register else { break }
            log(.attestationStepKeyGenerated, summary: "App Attest key generated — no network involved",
                detail: [DetailField(label: "Key ID", value: keyId)])
            RealAttemptCounter.keysGenerated.increment()
        case .attestationPending(_, let attestationData, _):
            let environment = AttestationEnvironmentHint.environment(of: attestationData)
            lastSeenEnvironment = environment
            if activeStep == .register {
                RealAttemptCounter.appleAttestations.increment()
            }
            if environment != .development {
                log(.attestationFailed,
                    summary: environment == .production
                        ? "⚠️ PRODUCTION attestation — Apple's response carries the production aaguid. Stop and check the entitlement and how this build was installed."
                        : "⚠️ attestation environment not recognised — the aaguid matches neither known marker; see the Environment field below",
                    isError: true)
            }
            log(.attestationStepAttested, summary: "CBOR attestation object received (\(attestationData.count) bytes)",
                detail: [
                    DetailField(label: "Format", value: "CBOR — {fmt, attStmt, authData}"),
                    DetailField(label: "Attestation object size", value: "\(attestationData.count) bytes"),
                    DetailField(label: "Environment", value: AttestationEnvironmentHint.describe(attestationData)),
                    // Full raw bytes, unmodified from what attestKey() returned.
                    // In-memory only (this history is never persisted), but this
                    // is the same category of sensitive data as keyId — the
                    // embedded cert contains the device's real App Attest
                    // public key. Never wire this field into anything that
                    // persists, syncs, or reaches a crash report.
                    DetailField(label: "Raw CBOR (hex)",
                                value: attestationData.map { String(format: "%02x", $0) }.joined())
                ])
        case .attested:
            // No log here — handleTransportEvent's .submitted case already
            // logs this same moment (with the actually useful detail, the
            // real account UUID). This transition is just its downstream
            // result; logging both would duplicate one real event.
            break
        case .unsupported:
            log(.attestationFailed, summary: "unsupported — real device required (Simulator always reports this)", isError: true)
        }
    }

    private func handleTransportEvent(_ event: TransportEvent) {
        switch event {
        case .challengeFetched(let byteCount):
            log(.attestationStepChallenge, summary: "GET /challenge → \(byteCount) random bytes")
        case .submitted(let accountUUID):
            // Persisted, not just logged — sign() needs this later to open a
            // real session, since AssertionSigning never hands the app a
            // keyId to use instead. See RegisteredAccountStore.swift.
            RegisteredAccountStore.current = accountUUID
            log(.attestationStepSubmitted, summary: "POST /register → Auth Server",
                detail: [DetailField(label: "Account UUID", value: accountUUID)])
        case .sessionOpened(let tokenByteCount):
            log(.assertionSigned, summary: "POST /session → Auth Server, session token issued (\(tokenByteCount) bytes)")
        case .paused(let point):
            log(.stepControl, summary: "PAUSED \(point) — tap Continue, or force-quit / cut the network first")
        case .resumed(let point):
            log(.stepControl, summary: "continued \(point)")
        case .requestFailed(let endpoint, let statusCode, let detail):
            // This is what the coordinator's own .networkUnavailable label
            // can't tell you: whether the server was ever actually reached.
            // nil statusCode = it wasn't (real connectivity/permission
            // problem); a real status = it was, and rejected the request —
            // an entirely different thing to go fix.
            let summary = statusCode.map { "\(endpoint) → HTTP \($0) (server reached, request rejected)" }
                ?? "\(endpoint) → no response (server never reached)"
            log(.attestationFailed, summary: summary,
                detail: [DetailField(label: "Detail", value: detail)], isError: true)
        }
    }

    private func log(_ kind: HarnessEvent.Kind, summary: String, detail: [DetailField] = [], isError: Bool = false) {
        let event = HarnessEvent(kind: kind, timestamp: Date(), summary: summary, detail: detail, isError: isError)
        sessions[sessions.count - 1].events.append(event)
    }

    private func startNewSession() {
        sessions.append(HarnessSession())
    }
}

/// Diagnostics only. Mostly keyId-omitting — see `recordTransition`'s doc
/// comment for the one deliberate, in-memory-only exception. keyId is a
/// persistent device identifier and this caution is the default; it's not
/// blanket-true of everything downstream of this observer. AttestationObserver's
/// methods are synchronous by design (the coordinator calls them in-line from
/// actor context), so this hops to MainActor explicitly rather than assuming one.
struct HarnessObserver: AttestationObserver {
    let onTransition: @Sendable (AttestationState) -> Void
    let onFailure: @Sendable (AttestationError, Int) -> Void

    func didTransition(to state: AttestationState) { onTransition(state) }
    func didFail(_ error: AttestationError, attempt: Int) { onFailure(error, attempt) }
}
