//
//  HarnessFlowModel.swift
//  AppAttestTestApp
//
//  Real version of the guided-sequence flow approved via the mock preview.
//  Drives AppAttestKit's real AttestationCoordinator against real
//  DCAppAttestService calls, under the development App Attest environment
//  (AppAttestTestApp.entitlements) — safe for repeated real-device testing,
//  since it doesn't count against the production per-device key budget
//  (confirmed this session — see account-keys-reference.md).
//
//  Which server (if any) it talks to is a debug setting (TransportBackend),
//  not hardcoded here — see the "Backend" section in HarnessFlowView. Both
//  LocalFakeTransport (Apple-side only, no server) and RealAttestationTransport
//  (Apple-side AND server-side both real) are selected at runtime.
//
//  Deliberately reads NOTHING from AppAttestKit except its public surface —
//  AttestationCoordinator.currentState — never LiveKeyStore/
//  AttestationKeyStore directly. That boundary is the module's core
//  guarantee (README.md: "the one thing to look for").
//

import Foundation
import CryptoKit
import AppAttestKit

@Observable @MainActor
final class HarnessFlowModel {
    enum ActiveStep { case none, identity, attest, sign }

    private(set) var identityGenerated = false
    private(set) var attested = false
    private(set) var activeStep: ActiveStep = .none
    private(set) var identityPublicKeyPrefix: String?

    /// Guards `RealAttemptCounter` against over-counting within a single
    /// attest() call. `transition()` fires the observer unconditionally, even
    /// for a no-op re-transition to the SAME .keyGenerated(keyId:) — which
    /// happens on every retry-loop re-entry into attemptRegistration() before
    /// state ever advances past .keyGenerated (e.g. /challenge failing
    /// repeatedly). Confirmed on a real device: 2 network retries before a
    /// working attempt logged 3 "key generated" events for what was really
    /// ONE generateKey() call. Reset at the start of each attest(); only a
    /// genuinely NEW keyId (never a DIFFERENT one — same keyId means "still
    /// the same generation, just observed again") increments the counter.
    private var lastCountedKeyId: String?

    /// Local heuristic only — Apple exposes no remaining-budget API
    /// (confirmed against current docs this session). Counts real
    /// generateKey() calls via the .keyGenerated transition — but only
    /// while an attest() call is actually in flight (see recordTransition);
    /// a bare restore() can ALSO transition into .keyGenerated by reading an
    /// existing keyId off disk, with no real generateKey() call involved.
    /// Keychain-backed, not UserDefaults, so it survives reinstall — the
    /// real budget it's tracking does too.
    var realAttemptCount: Int {
        RealAttemptCounter.load()
    }

    /// One entry per attempt. "Reset module state" and "Delete identity key"
    /// close out the current session and open a fresh one.
    var sessions: [HarnessSession] = [HarnessSession()]

    var stateLabel: String {
        if attested { return "attested" }
        if identityGenerated { return "identity ready (App Attest not yet requested)" }
        return "none"
    }

    /// Changing this doesn't touch identity/attestation state — those
    /// reflect the DEVICE's own Keychain-persisted state, independent of
    /// which server it's pointed at. Switching backends mid-session and then
    /// tapping Sign against a server that's never seen this device's keyId
    /// is expected to fail server-side — that's correct, not a harness bug.
    var transportBackend: TransportBackend {
        get { TransportBackend.current }
        set {
            guard newValue != TransportBackend.current else { return }
            TransportBackend.current = newValue
            // Cached coordinator holds the OLD transport — drop it so the
            // next resolveCoordinator() rebuilds against the new backend.
            coordinator = nil
            log(.backendSwitched, summary: "switched to \(newValue.displayName)")
        }
    }

    private var coordinator: AttestationCoordinator?
    private static let hasLaunchedBeforeKey = "harness.hasLaunchedBefore"
    private let firstLaunchGate = FirstLaunchPurgeGate.standard(key: hasLaunchedBeforeKey)
    private var firstLaunchTask: Task<Void, Never>?

    /// Call once when the view appears.
    ///
    /// First checks whether this is the first launch after an install OR a
    /// reinstall (the `UserDefaults` flag is absent either way — wiped along
    /// with the rest of the sandbox container on delete, unlike Keychain).
    /// If so, purges any stale Keychain leftovers from a PREVIOUS install
    /// before showing any state — this is the proactive half of the v1
    /// policy (appattestkit-module-design.md §8): the UI should never show a
    /// misleadingly "attested" status after a reinstall, even briefly.
    /// `sign()`'s own `acknowledgeKeyInvalidation()` call remains as a
    /// reactive safety net for invalidation that happens WITHOUT a reinstall
    /// (e.g. a device restore) — this gate does not replace it.
    ///
    /// Otherwise (normal, non-first launch), just reflects whatever's
    /// already persisted — critical for the kill-and-relaunch smoke test
    /// (appattest-smoke-checklist.md item 4): without this, the UI would
    /// always show "not started" even after a real prior attestation.
    func restoreOnAppear() async {
        let coordinator = resolveCoordinator()
        await runFirstLaunchGateOnce(coordinator: coordinator)

        identityGenerated = IdentityKeyStore.exists()
        guard identityGenerated else { return }
        if let key = try? IdentityKeyStore.loadOrCreate() {
            identityPublicKeyPrefix = key.publicKey.rawRepresentation.prefix(4)
                .map { String(format: "%02x", $0) }.joined()
        }
        await coordinator.restore()
        let state = await coordinator.currentState
        attested = state.isAttested
        // Structured, not just embedded in the summary text — HarnessSession
        // needs to reliably tell "restored into an already-attested state"
        // apart from "restored into something else," and matching against
        // free text would be fragile.
        log(.restored, summary: "found existing state on launch: \(state.label)",
            detail: [DetailField(label: "Restored as attested", value: state.isAttested ? "yes" : "no")])
    }

    /// Deduplicates concurrent calls the same way
    /// `AttestationCoordinator.ensureAttested()` does (an in-flight `Task`)
    /// — `restoreOnAppear()` being invoked more than once concurrently
    /// (today there's one call site, but this is exactly the multi-trigger
    /// shape — launch, foreground, connectivity change — the module's own
    /// docs anticipate for `ensureAttested()`) must not let the purge run
    /// twice.
    ///
    /// Deliberately does NOT reset `firstLaunchTask` to `nil` after
    /// completion the way the coordinator resets `inFlight` — the
    /// coordinator needs to support meaningful NEW runs later (state can
    /// change between calls), but this gate is a true "at most once per
    /// launch" check: once it's resolved, every later call in this same
    /// process should just re-await the same finished `Task` for free,
    /// rather than re-doing even the cheap `UserDefaults` read.
    private func runFirstLaunchGateOnce(coordinator: AttestationCoordinator) async {
        if let firstLaunchTask {
            await firstLaunchTask.value
            return
        }
        let task = Task {
            await self.firstLaunchGate.runIfNeeded {
                // Conditional on purge is required, not optional: a genuine
                // first-ever install ALSO has this flag absent, with nothing
                // in Keychain to purge. Calling acknowledgeKeyInvalidation()
                // unconditionally here would spend budget on a brand-new
                // user's first launch for nothing.
                let hadIdentity = IdentityKeyStore.exists()
                if hadIdentity {
                    IdentityKeyStore.delete()
                }
                await coordinator.restore()
                let hadModuleState = await coordinator.currentState != .none
                var purgeSucceeded = true
                if hadModuleState {
                    purgeSucceeded = await coordinator.acknowledgeKeyInvalidation()
                    if !purgeSucceeded {
                        // Real, visible failure — this used to be silently
                        // reported as success (discarded return value), which
                        // is exactly the wrong failure mode for a permanent
                        // lockout. See AttestationCoordinator.debugResetRegenerationBudget
                        // for why a harness-only reset exists at all: this
                        // counter has no reset path in a shipping build, on
                        // purpose, but a test device legitimately hits
                        // maxKeyRegenerations from repeated testing, not a bug.
                        self.log(.attestationFailed,
                                 summary: "regeneration budget exhausted — using the harness-only debug reset to stay unblocked (never available in a shipping build)",
                                 isError: true)
                        #if DEBUG
                        await coordinator.debugResetRegenerationBudget()
                        purgeSucceeded = await coordinator.acknowledgeKeyInvalidation()
                        #endif
                    }
                }
                if hadIdentity || hadModuleState {
                    // Stale from whatever registration this Keychain state
                    // belonged to — a reinstall guarantees the NEXT
                    // registration (if any) will mint a different
                    // account_uuid (v1: no re-attestation), so keeping the
                    // old one around would let sign() try to open a session
                    // for an account this device can no longer prove it owns.
                    RegisteredAccountStore.current = nil
                    self.log(.identityKeyDeleted,
                             summary: purgeSucceeded
                                ? "first launch after install/reinstall — purged stale Keychain state from a previous install"
                                : "first launch after install/reinstall — purge did NOT fully succeed, even after a debug regeneration-budget reset",
                             isError: !purgeSucceeded)
                    self.startNewSession()
                } else {
                    self.log(.restored, summary: "first launch — Keychain already clean, nothing to purge")
                }
            }
        }
        firstLaunchTask = task
        await task.value
    }

    func generateIdentity() async {
        guard activeStep == .none else { return }
        activeStep = .identity
        defer { activeStep = .none }
        do {
            let key = try IdentityKeyStore.loadOrCreate()
            let prefix = key.publicKey.rawRepresentation.prefix(4)
                .map { String(format: "%02x", $0) }.joined()
            identityGenerated = true
            identityPublicKeyPrefix = prefix
            log(.identityKeyGenerated, summary: "identity key ready (\(prefix)…)",
                detail: [DetailField(label: "Public key prefix", value: prefix)])
        } catch {
            log(.identityKeyGenerationFailed, summary: "\(error)", isError: true)
        }
    }

    /// The one real atomic call — see the file header for why this can't be
    /// split any further than "identity, then attest."
    func attest() async {
        guard activeStep == .none else { return }
        activeStep = .attest
        lastCountedKeyId = nil
        defer { activeStep = .none }

        // Existence check only — RealAttestationTransport reads the identity
        // public key itself (independently, per /challenge and /register
        // call) now that clientDataHash no longer embeds it here.
        guard identityGenerated, (try? IdentityKeyStore.loadOrCreate()) != nil else {
            let summary = identityGenerated
                ? "identity key unavailable despite being marked generated — try Delete Identity Key and Generate again"
                : "no identity key — generate one first"
            log(.attestationFailed, summary: summary, isError: true)
            return
        }

        log(.attestationStarted, summary: "attestation flow started")

        let coordinator = resolveCoordinator()
        do {
            // clientDataHash = SHA256(challenge) alone, NOT SHA256(challenge +
            // identityPublicKey) — this used to concatenate the identity key
            // in, matching an earlier design. Revised when the real Auth
            // Server was built: the verification library it uses fixes this
            // hash formula with no override seam, so the identity binding
            // moved server-side instead (the challenge is issued bound to an
            // identityPublicKey and checked back at /register — see
            // RealAttestationTransport.swift and account-keys-reference.md).
            let result = try await coordinator.ensureAttested { challenge in
                Data(SHA256.hash(data: challenge))
            }
            if result.isAttested {
                attested = true
            } else {
                log(.attestationFailed, summary: "ended in state: \(result.label)", isError: true)
            }
        } catch let error as AttestationError {
            log(.attestationFailed, summary: error.diagnosticName, isError: true)
        } catch {
            log(.attestationFailed, summary: "\(error)", isError: true)
        }
    }

    /// The Secure Enclave signing itself is cheap, repeatable, purely local,
    /// no network at all (confirmed via web search this session). Whether
    /// this ALSO opens a real session against the Auth Server depends on the
    /// backend — .mock never did and still doesn't (nothing to submit to);
    /// .localDocker/.custom now actually call /session/nonce + /session,
    /// which they did NOT do before this was found and fixed: this used to
    /// fabricate a nonce locally and sign it with no server involved at all,
    /// under ANY backend — "Assertion Signed" could appear in History with
    /// no /session request ever reaching the server. See SessionClient.swift.
    func sign() async {
        guard activeStep == .none else { return }
        guard let coordinator else {
            log(.signFailed, summary: "sign attempted before attesting", isError: true)
            return
        }
        activeStep = .sign
        defer { activeStep = .none }
        do {
            switch transportBackend {
            case .mock:
                let nonce = Data((0..<32).map { _ in UInt8.random(in: 0...255) })
                let signature = try await coordinator.sign(Data(SHA256.hash(data: nonce)))
                log(.assertionSigned, summary: "assertion signed, mock only — no server involved (\(signature.count) bytes)",
                    detail: [DetailField(label: "Signature size", value: "\(signature.count) bytes")])
            case .localDocker, .custom:
                guard let accountUuid = RegisteredAccountStore.current else {
                    log(.signFailed, summary: "no stored account UUID — Attest must complete successfully first", isError: true)
                    return
                }
                let client = SessionClient(
                    baseURL: currentBaseURL(),
                    signer: coordinator,
                    onEvent: { [weak self] event in
                        Task { @MainActor in self?.handleTransportEvent(event) }
                    })
                // No explicit success log here, deliberately — matching how
                // attest() doesn't log its own success either: the real
                // events (.challengeFetched, .sessionOpened, ...) come
                // through onEvent as they actually happen, so logging again
                // here would duplicate the one that matters.
                _ = try await client.openSession(accountUuid: accountUuid)
            }
        } catch let error as AttestationError {
            log(.signFailed, summary: error.diagnosticName, isError: true)
            // Confirmed on real hardware (a delete+reinstall's orphaned keyId):
            // Apple's generateAssertion() surfaces this as DCError.invalidInput
            // → .serverRejected("invalidInput"), NOT .keyInvalid as originally
            // assumed — see the warning in AttestationError.swift this proved
            // right. Safe to treat as equivalent to .keyInvalid specifically
            // HERE: this call's clientDataHash is always a freshly-computed
            // SHA256 digest, never app-malformed, so an "invalidInput" rejection
            // at THIS call site can only mean the keyId itself is dead.
            if error == .keyInvalid || error == .serverRejected("invalidInput") {
                // v1 policy (appattestkit-module-design.md §8, revised): wipe
                // the identity key TOGETHER with module state, always — never
                // one without the other. The earlier version of this handler
                // only called acknowledgeKeyInvalidation(), which is exactly
                // the gap that method closes, but preserving identity here
                // would reintroduce the two-path complexity that decision
                // deliberately traded away for a faster v1 ship.
                IdentityKeyStore.delete()
                RegisteredAccountStore.current = nil
                identityPublicKeyPrefix = nil
                let recovered = await coordinator.acknowledgeKeyInvalidation()
                identityGenerated = false
                attested = false
                log(.identityKeyDeleted, summary: recovered
                    ? "key invalidation acknowledged — identity and module state both cleared (v1 policy), next Generate/Attest starts fully fresh"
                    : "key invalidation acknowledged, but regeneration budget exhausted",
                    isError: !recovered)
                startNewSession()
            }
        } catch {
            log(.signFailed, summary: "\(error)", isError: true)
        }
    }

    /// Matches Option A (appattestkit-module-design.md §8): resetting module
    /// state does NOT touch the identity key.
    func resetModuleState() async {
        #if DEBUG
        if let coordinator {
            await coordinator.debugReset()
        }
        RegisteredAccountStore.current = nil
        attested = false
        log(.moduleReset, summary: "module state cleared — identity key kept, matches Option A. Next Attest spends a real key generation.")
        startNewSession()
        #else
        log(.attestationFailed, summary: "debugReset is DEBUG-only", isError: true)
        #endif
    }

    func deleteIdentityKey() async {
        IdentityKeyStore.delete()
        RegisteredAccountStore.current = nil
        identityGenerated = false
        attested = false
        identityPublicKeyPrefix = nil
        #if DEBUG
        // Without this, the coordinator's in-memory state can still say
        // .attested from before the delete — and AttestationCoordinator.run()
        // returns immediately on `state.isAttested`, without ever contacting
        // Apple again, for an identity that no longer matches it.
        if let coordinator {
            await coordinator.debugReset()
        }
        log(.identityKeyDeleted, summary: "identity key and module state cleared — next Attest starts fully fresh")
        #else
        log(.identityKeyDeleted, summary: "identity key deleted, but debugReset is DEBUG-only — module state may still read attested", isError: true)
        #endif
        startNewSession()
    }

    // MARK: - Wiring

    private func resolveCoordinator() -> AttestationCoordinator {
        if let coordinator { return coordinator }
        let transport = makeTransport()
        let observer = HarnessObserver(
            onTransition: { [weak self] state in
                Task { @MainActor in self?.recordTransition(state) }
            },
            onFailure: { [weak self] error, attempt in
                Task { @MainActor in
                    self?.log(.attestationFailed, summary: "\(error.diagnosticName) (attempt \(attempt))", isError: true)
                }
            })
        let coordinator = AttestationCoordinator(transport: transport, observer: observer)
        self.coordinator = coordinator
        return coordinator
    }

    private func makeTransport() -> AttestationTransport {
        let identityPublicKeyBase64: () -> String = {
            guard let key = try? IdentityKeyStore.loadOrCreate() else { return "" }
            return key.publicKey.rawRepresentation.base64EncodedString()
        }
        let onEvent: @Sendable (TransportEvent) -> Void = { [weak self] event in
            Task { @MainActor in self?.handleTransportEvent(event) }
        }
        switch transportBackend {
        case .mock:
            return LocalFakeTransport(onEvent: onEvent)
        case .localDocker, .custom:
            return RealAttestationTransport(
                baseURL: currentBaseURL(),
                identityPublicKeyBase64: identityPublicKeyBase64,
                onEvent: onEvent)
        }
    }

    /// Shared by makeTransport() and sign()'s real-backend branch — both
    /// need to agree on which server they're pointed at.
    private func currentBaseURL() -> URL {
        switch transportBackend {
        case .mock, .localDocker: return AuthServerConfig.baseURL
        case .custom(let url): return url
        }
    }

    /// NEVER interpolate a state's associated keyId directly — `.label` is
    /// deliberately the safe, keyId-omitting summary (architecture doc §10).
    private func recordTransition(_ newState: AttestationState) {
        switch newState {
        case .none:
            break
        case .keyGenerated(let keyId):
            log(.attestationStepKeyGenerated, summary: "App Attest key generated — no network involved")
            // Only count transitions observed during an ACTIVE attest() call.
            // restore() can also transition into .keyGenerated merely by
            // reading an existing keyId back off disk (no real generateKey()
            // call involved) — and restore() now runs unconditionally on
            // every launch, plus again inside the first-launch purge gate.
            // Counting those would inflate this heuristic on every ordinary
            // launch that happens to find a mid-flow-crashed state.
            //
            // AND: only count it once per DISTINCT keyId within this call —
            // see lastCountedKeyId's doc comment for why a retry loop can
            // reflect the same .keyGenerated state multiple times with no
            // new generateKey() call in between.
            if activeStep == .attest, keyId != lastCountedKeyId {
                lastCountedKeyId = keyId
                RealAttemptCounter.increment()
            }
        case .attestationPending(_, let attestationData, _):
            log(.attestationStepAttested, summary: "CBOR attestation object received (\(attestationData.count) bytes)",
                detail: [
                    DetailField(label: "Format", value: "CBOR — {fmt, attStmt, authData}"),
                    DetailField(label: "Attestation object size", value: "\(attestationData.count) bytes"),
                    DetailField(label: "Environment", value: AttestationEnvironmentHint.describe(attestationData)),
                    // Full raw bytes, unmodified from what attestKey() returned.
                    // In-memory only (this history is never persisted), but this
                    // is the same category of sensitive data as keyId — the
                    // embedded cert contains the device's real App Attest
                    // public key. Never wire this field into anything that
                    // persists, syncs, or reaches a crash report.
                    DetailField(label: "Raw CBOR (hex)",
                                value: attestationData.map { String(format: "%02x", $0) }.joined())
                ])
        case .attested:
            // No log here — handleTransportEvent's .submitted case already
            // logs this same moment (with the actually useful detail, the
            // real account UUID). This transition is just its downstream
            // result; logging both would duplicate one real event.
            break
        case .unsupported:
            log(.attestationFailed, summary: "unsupported — real device required (Simulator always reports this)", isError: true)
        }
    }

    private func handleTransportEvent(_ event: TransportEvent) {
        switch event {
        case .challengeFetched(let byteCount):
            log(.attestationStepChallenge, summary: "GET /challenge → \(byteCount) random bytes")
        case .submitted(let accountUUID):
            // Persisted, not just logged — sign() needs this later to open a
            // real session, since AssertionSigning never hands the app a
            // keyId to use instead. See RegisteredAccountStore.swift.
            RegisteredAccountStore.current = accountUUID
            log(.attestationStepSubmitted, summary: "POST /register → Auth Server",
                detail: [DetailField(label: "Account UUID", value: accountUUID)])
        case .sessionOpened(let tokenByteCount):
            log(.assertionSigned, summary: "POST /session → Auth Server, session token issued (\(tokenByteCount) bytes)")
        case .requestFailed(let endpoint, let statusCode, let detail):
            // This is what the coordinator's own .networkUnavailable label
            // can't tell you: whether the server was ever actually reached.
            // nil statusCode = it wasn't (real connectivity/permission
            // problem); a real status = it was, and rejected the request —
            // an entirely different thing to go fix.
            let summary = statusCode.map { "\(endpoint) → HTTP \($0) (server reached, request rejected)" }
                ?? "\(endpoint) → no response (server never reached)"
            log(.attestationFailed, summary: summary,
                detail: [DetailField(label: "Detail", value: detail)], isError: true)
        }
    }

    private func log(_ kind: HarnessEvent.Kind, summary: String, detail: [DetailField] = [], isError: Bool = false) {
        let event = HarnessEvent(kind: kind, timestamp: Date(), summary: summary, detail: detail, isError: isError)
        sessions[sessions.count - 1].events.append(event)
    }

    private func startNewSession() {
        sessions.append(HarnessSession())
    }
}

/// Diagnostics only — NEVER logs a keyId, which is a persistent device
/// identifier (architecture doc §10). AttestationObserver's methods are
/// synchronous by design (the coordinator calls them in-line from actor
/// context), so this hops to MainActor explicitly rather than assuming one.
struct HarnessObserver: AttestationObserver {
    let onTransition: @Sendable (AttestationState) -> Void
    let onFailure: @Sendable (AttestationError, Int) -> Void

    func didTransition(to state: AttestationState) { onTransition(state) }
    func didFail(_ error: AttestationError, attempt: Int) { onFailure(error, attempt) }
}
